name: .NET Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-lates  # You can also use 'windows-latest' or 'macos-latest'

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up .NET SDK
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change this to the version of .NET you're using

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the project
    - name: Build the project
      run: dotnet build --configuration Release

    # Step 5: Run tests (if applicable)
    - name: Run tests
      run: dotnet test --configuration Release

    # Step 6: Publish the application
    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish

    # Step 7: Upload artifacts for deployment (if needed)
    - name: Upload published app
      uses: actions/upload-artifact@v2
      with:
        name: mvc-app
        path: ./publish
